# Generated by Django 6.0.6 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
